markdown: rdiscount
permalink: /:title/
url: http://zhuming.in
name: zhuming.in
author: Zhuming
email: shuiyao2@foxmail.com
duoshuo: shuiyao2
github: shuiyao2
pygments: true
safe: true
paginate: 20
about: "i love Python"
